### NUMPY

# NumPy is a Python library.
# NumPy is used for working with arrays.
# NumPy is short for "Numerical Python".
# ->Library or modules
# ->OS,socket,numpy
# ->pip install numpy
# ->array is to be created
# ->list is used for small purpose
# ->numpy is used for big problem
# ->numpy is an array 
#->                                     NUMPY FUNCTION
#-> np.arange                                           #only give 1D array
#-> np.ones(10)                                         # gives one 10 times
#-> np.zeros((10,5))                                    # gives the zeros in a matrix
#-> np.linspace(1,8,5)                                  #in between 1 to 8 divide 5 items
#->                                     RANDOM FUNCTION:-
#-> random.randint(1,10)                                # gives the output as a random number betwwen 1 to 10
#-> random.random()                                     #only in between 0 to 1
#-> random.choice(ls)                                   # randomly choice in between the list
#-> random.choices(ls,k=2)                              # randomly give the two output from the list
#-> random.shuffle(ls)                                  # it shuffle the list
#-> np.random.randint(1,50,10)                          #in between 1 to 50 with filling 10 items
#-> np.arange(60)
#-> arr.reshape(12,5)                                   # it divide arr in 12 row and 5 column
#-> np.resize(arr,(25,25))                              #it resize the arr in 25*25 
#-> arr2.ndim                                           # it tells the dinemension of the arr2
#-> arr2.ravel()                                        #converting any dimension into 1D function
#-> arr2.flatten()                                      #converting into 1D  work same as revel


IMPORT NUMPY....

In [2]:
import numpy as np
print("numpy is install")

numpy is install


CREATE A LIST

In [4]:
ls =[42,34,56,43,45,34,23,54,68,98]
ls

[42, 34, 56, 43, 45, 34, 23, 54, 68, 98]

FINDING THE TYPE OF ARRAY

In [6]:
arr=np.array(ls)  #it became array ->n dimensional array
arr
type(arr)

numpy.ndarray

NUMPY ARRAY

In [3]:
ls=[42, 34, 56, 43, 45, 34, 23, 54, 68, 98.8] #"upflairs"]
arr=np.array(ls) #python flexibility
arr
# Array only stored similar data items

array([42. , 34. , 56. , 43. , 45. , 34. , 23. , 54. , 68. , 98.8])

ARRAY TYPE

In [18]:
arr.dtype

dtype('float64')

ADDING 5 TO EACH ELEMENT OF ARRAY

In [7]:
arr +5  # it increse by 5

array([ 47,  39,  61,  48,  50,  39,  28,  59,  73, 103])

FETCHING THE ELEMENT AT THE INDEX

In [4]:
arr[2]  #O(1)

np.float64(56.0)

MULTIPLY THE ARRAY

In [8]:
arr*234567

array([ 9851814,  7975278, 13135752, 10086381, 10555515,  7975278,
        5395041, 12666618, 15950556, 22987566])

FINDING THE DIMENSION

In [ ]:
arr.ndim # no. of dimension

# [25,45,67] ->1D
# [[],[],[]] ->2D

In [ ]:
# ARRAY.....
# ->collection of similar item
# ->continous memory allocation
# ->first address+(index*data type)

CREATING THE LIST

In [21]:
ls=[45,7,84,56,45,78,34,78,43,35]
arr =np.array(ls)
arr


array([45,  7, 84, 56, 45, 78, 34, 78, 43, 35])

FINDING THE ELEMENT

In [23]:
arr[2:5]

array([84, 56, 45])

FINDING THE ARRAY SIZE

In [26]:
arr.size

10

In [27]:
len(arr)  #polymorphism

10

In [33]:
for i in arr:
    if i > 50:
        print(i)

84
56
78
78


In [35]:
arr[arr>50]


array([84, 56, 78, 78])

In [36]:
arr.shape

(10,)

In [37]:
arr2=np.arange(50)   #only give 1D array
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
np.ones(10) # gives one 10 times

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones((10,5)) #2D

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.zeros((10,5))  # gives the zeros in a matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.linspace(1,8,5)  #in between 1 to 8 divide 5 items

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [6]:
import random

In [49]:
random.randint(1,10)  # gives the output as a random number betwwen 1 to 10

5

In [53]:
random.random()   #only in between 0 to 1

0.5172678940445693

In [7]:
ls=["arushii","nikita","pragati","kritik","princy"]
ls

['arushii', 'nikita', 'pragati', 'kritik', 'princy']

In [55]:
random.choice(ls)  # randomly choice in between the list

'pragati'

In [59]:
random.choices(ls,k=2) # randomly give the two output from the list

['pragati', 'pragati']

In [8]:
random.shuffle(ls)   # it shuffle the list

In [61]:
ls

['nikita', 'princy', 'kritik', 'pragati', 'arushii']

In [62]:
np.random.randint(1,50,10)  #in between 1 to 50 with filling 10 items

array([32, 32, 24, 23, 45, 31, 46, 18, 22, 34], dtype=int32)

In [64]:
!python --version

Python 3.12.2


In [65]:
np.random.randint(1,50,(10,5)) 

array([[13, 28, 47,  1, 28],
       [41, 29, 25, 18,  2],
       [31, 17, 41, 16, 39],
       [48, 42, 19, 29, 30],
       [30, 47, 25, 25,  3],
       [ 4, 42, 21, 13,  4],
       [30, 29,  9,  7, 40],
       [ 2, 47, 22,  3, 41],
       [42, 37, 44, 43, 49],
       [27, 49,  6, 11, 45]], dtype=int32)

In [67]:
np.arange(60)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [68]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [69]:
arr.reshape(12,5)  # it divide arr in 12 row and 5 column

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [70]:
arr.reshape(10,2,3) # it divide arr in 10 2 3 matrix

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41]],

       [[42, 43, 44],
        [45, 46, 47]],

       [[48, 49, 50],
        [51, 52, 53]],

       [[54, 55, 56],
        [57, 58, 59]]])

In [73]:
np.resize(arr,(25,25))  #it resize the arr in 25*25 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 

In [74]:
arr2=np.resize(arr,(25,25))
arr2.shape

(25, 25)

In [75]:
arr2.ndim  # it tells the dinemension of the arr2

2

In [76]:
# reshape 1-> 2D , 3D
arr2.reshape(625,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [78]:
arr2.ravel()  #converting any dimension into 1D function

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [79]:
arr2.flatten()  #converting into 1D  work same as revel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45

In [9]:
arr=np.random.randint(5,50,100)
arr

array([36, 36, 18, 46, 36, 19,  6, 39, 40, 34, 40, 21, 16, 25, 41, 41,  6,
       25,  7, 25, 32, 33, 14, 43, 13, 13, 49, 13, 21, 20, 27, 39, 14, 26,
       40, 27, 38, 32, 34, 16, 27, 23, 19, 15,  8, 31, 28, 49, 37, 29, 27,
       25, 42, 17, 39, 32, 24, 26, 39, 45, 35, 14, 24, 34, 15, 28,  9, 37,
       49, 37, 47, 26, 43,  6, 15, 11, 41,  5, 25, 28, 16, 25, 35, 49, 45,
       47, 47, 24, 35, 44, 39, 19, 24, 41, 44, 26, 42, 12, 17,  6],
      dtype=int32)

In [10]:
arr.min()

np.int32(5)

In [11]:
arr.max()

np.int32(49)

In [12]:
arr.sum()

np.int64(2849)

In [13]:
arr.mean()   #mean()=average()

np.float64(28.49)

In [14]:
arr=np.random.randint(5,50,(4,3))
arr

array([[30,  5, 28],
       [25, 23, 46],
       [35, 37, 21],
       [31, 32, 34]], dtype=int32)

In [15]:
arr.ndim

2

In [17]:
arr.shape

(4, 3)

In [18]:
np.transpose(arr)  #switch column to row

array([[30, 25, 35, 31],
       [ 5, 23, 37, 32],
       [28, 46, 21, 34]], dtype=int32)

In [19]:
np.transpose(arr).shape

(3, 4)

In [20]:
arr.T

array([[30, 25, 35, 31],
       [ 5, 23, 37, 32],
       [28, 46, 21, 34]], dtype=int32)

In [22]:
arr = np.random.randint(2,12,(10,5))
arr

array([[ 5, 10,  6,  4, 11],
       [ 6,  2,  9, 11,  4],
       [11,  3,  6,  3,  3],
       [11,  3,  3, 10, 10],
       [ 6,  9,  7,  8,  7],
       [ 2, 11,  4,  9,  4],
       [ 7,  9,  2,  9,  7],
       [ 2,  6,  2,  2, 11],
       [ 9,  5,  2, 10,  6],
       [11,  4, 11, 11,  5]], dtype=int32)

In [28]:
arr.ravel()
arr.flatten()
arr.reshape(50,)

array([ 5, 10,  6,  4, 11,  6,  2,  9, 11,  4, 11,  3,  6,  3,  3, 11,  3,
        3, 10, 10,  6,  9,  7,  8,  7,  2, 11,  4,  9,  4,  7,  9,  2,  9,
        7,  2,  6,  2,  2, 11,  9,  5,  2, 10,  6, 11,  4, 11, 11,  5],
      dtype=int32)

In [29]:
arr[0]   #array(start_row,stop_row)

array([ 5, 10,  6,  4, 11], dtype=int32)

In [30]:
arr[-1]

array([11,  4, 11, 11,  5], dtype=int32)

In [33]:
arr[2:5]

array([[11,  3,  6,  3,  3],
       [11,  3,  3, 10, 10],
       [ 6,  9,  7,  8,  7]], dtype=int32)

In [34]:
arr[7:10]

array([[ 2,  6,  2,  2, 11],
       [ 9,  5,  2, 10,  6],
       [11,  4, 11, 11,  5]], dtype=int32)

In [35]:
arr[7:]

array([[ 2,  6,  2,  2, 11],
       [ 9,  5,  2, 10,  6],
       [11,  4, 11, 11,  5]], dtype=int32)

In [38]:
arr[0:,0:2]

array([[ 5, 10],
       [ 6,  2],
       [11,  3],
       [11,  3],
       [ 6,  9],
       [ 2, 11],
       [ 7,  9],
       [ 2,  6],
       [ 9,  5],
       [11,  4]], dtype=int32)

In [39]:
arr[:,:2]

array([[ 5, 10],
       [ 6,  2],
       [11,  3],
       [11,  3],
       [ 6,  9],
       [ 2, 11],
       [ 7,  9],
       [ 2,  6],
       [ 9,  5],
       [11,  4]], dtype=int32)

In [42]:
arr[3:6,2:5]

array([[ 3, 10, 10],
       [ 7,  8,  7],
       [ 4,  9,  4]], dtype=int32)

In [45]:
arr[0::2,2:]  #here:2 is a jump point

array([[ 6,  4, 11],
       [ 6,  3,  3],
       [ 7,  8,  7],
       [ 2,  9,  7],
       [ 2, 10,  6]], dtype=int32)

In [47]:
arr = np.random.randint(2,50,(5,10,5))
arr

array([[[10, 32,  9, 40, 17],
        [ 9, 20, 15, 16, 15],
        [ 9, 33, 24, 19, 14],
        [39,  7, 24, 16, 49],
        [40, 47, 48,  5, 17],
        [49,  8, 29, 41, 38],
        [24, 25, 35,  8, 11],
        [24, 20, 30, 48, 29],
        [48, 26, 38, 34, 43],
        [29, 13, 25,  6, 44]],

       [[26, 23, 24,  9, 16],
        [47, 10, 15, 48, 14],
        [32, 40, 37, 42, 29],
        [24, 21,  4,  6, 33],
        [35, 43, 16, 40,  6],
        [49,  2, 18, 30, 13],
        [ 3, 36, 24, 38, 35],
        [12, 33, 40,  4, 33],
        [18, 29, 15, 19,  3],
        [41, 29, 15, 39, 27]],

       [[42,  9, 36,  9,  4],
        [32, 35,  9, 33, 36],
        [46, 11,  9, 11, 37],
        [35, 33, 18, 18, 22],
        [29, 17, 30, 15,  4],
        [25, 34, 23, 45,  8],
        [13, 49, 39, 35, 46],
        [22, 33, 33, 44, 35],
        [35, 17,  3, 37, 21],
        [43, 39, 15, 12, 20]],

       [[ 5,  6, 28, 22,  3],
        [29, 47, 14, 28, 36],
        [25, 48, 13, 20,  3],
    

In [48]:
arr.shape 
# 5Table,10 row,5 column

(5, 10, 5)

In [49]:
arr.ndim

3

In [50]:
arr[0]  #table single output table

array([[10, 32,  9, 40, 17],
       [ 9, 20, 15, 16, 15],
       [ 9, 33, 24, 19, 14],
       [39,  7, 24, 16, 49],
       [40, 47, 48,  5, 17],
       [49,  8, 29, 41, 38],
       [24, 25, 35,  8, 11],
       [24, 20, 30, 48, 29],
       [48, 26, 38, 34, 43],
       [29, 13, 25,  6, 44]], dtype=int32)

In [51]:
arr[0,8:,2:]  #arr[start:end:jump]

array([[38, 34, 43],
       [25,  6, 44]], dtype=int32)

In [52]:
arr[:,9:,]

array([[[29, 13, 25,  6, 44]],

       [[41, 29, 15, 39, 27]],

       [[43, 39, 15, 12, 20]],

       [[34, 16, 25, 22,  4]],

       [[47, 33, 10,  3, 29]]], dtype=int32)

In [63]:
arr=np.array([7,5,9])
arr

array([7, 5, 9])

In [55]:
arr.max()

np.int64(9)

In [56]:
arr.argmax()   #max item index

np.int64(2)

In [57]:
arr.argmin()  #min item index

np.int64(1)

In [60]:
arr.sort()
arr

array([5, 7, 9])

In [ ]:
arr.sort(reversed=True)

In [64]:
arr

array([7, 5, 9])

In [65]:
arr.argsort()  #sorting the index

array([1, 0, 2])

In [68]:
arr = np.random.randint(2,12,(10,5))

In [69]:
np.unique(arr)   #total unique item

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [ ]:
# variance
# mean
# median
# standard deviation
# linear based operation
# matrix operation


In [70]:
arr.mean()

np.float64(5.6)

In [72]:
arr = np.random.randint(2,250,200)
arr

array([176, 149, 118, 129,  98, 231, 204, 152, 156, 143,   6,  42, 114,
       125,  65,  66,  67, 112, 180, 105, 247, 186,  99, 103,  67, 239,
       110, 105,  17,  52,  65, 146, 106,  57,  91, 183, 207, 120, 153,
       217, 178, 127, 234, 143,  42,  89, 245,  58, 170,  80,  18,  63,
         3,  51, 180, 160, 248, 195,  55, 205, 152,  14, 160,  24, 182,
        60, 134, 172, 136, 223,  67,  93,  96, 104,  54,  68, 142, 239,
        42, 233, 162, 150,  92, 142,  21,  74, 144,  15,  24, 126, 242,
        64,  12, 116, 141,  55, 207, 190,  37,  33, 241,  10,  90, 130,
        96, 169, 189, 225, 204,  47,  50, 132,  95, 123, 246, 130, 118,
       216, 102, 183,  99, 172, 123,  69, 248,  30, 145,  77, 131, 128,
       177, 208, 112, 238, 179,  78, 107,  61,  35, 179, 191, 121,  87,
        38, 163, 247,  39,  46, 173, 147, 161, 124,  12,  45, 195,   3,
        27, 240,  66,  74, 140,  56, 178,  72, 193, 205,  81, 111, 171,
       136,  63, 146,  78,   9, 128,  75,  73, 238, 211,  78,  6

In [73]:
arr.var()

np.float64(4607.3691)

In [74]:
np.median(arr)

np.float64(119.5)

In [75]:
arr.std()

np.float64(67.87760381745956)

In [76]:
np.sqrt(25)

np.float64(5.0)

In [ ]:
# PANDAS.....

In [ ]:
# !pip install pandas

In [78]:
import pandas as pd
print("imported")

imported


In [9]:
arr = np.random.randint(2,50,(5,5,5))
arr

array([[[10, 21, 38, 10, 17],
        [35, 24, 45, 47,  7],
        [34,  7, 48, 17, 41],
        [45, 28, 18, 42, 37],
        [34, 23, 21,  7, 34]],

       [[49, 42, 12, 12, 24],
        [41, 28,  9, 19, 11],
        [21, 48, 40, 12, 42],
        [ 5, 12, 35,  2, 33],
        [40, 30, 15, 14, 29]],

       [[27, 18, 19,  8, 27],
        [28,  8, 40,  7, 10],
        [18,  8, 10, 14, 25],
        [27, 11, 48, 17,  5],
        [20, 44, 24, 40, 26]],

       [[23, 39,  3, 11, 12],
        [38, 39,  2,  5, 26],
        [24,  7, 18, 11, 31],
        [30, 34,  8, 35,  8],
        [ 6, 29, 43, 38, 34]],

       [[20, 29, 48, 41,  2],
        [48, 31, 21, 30, 14],
        [40, 23, 20, 47, 18],
        [ 6, 47, 25, 41, 16],
        [15, 23, 28, 14, 40]]], dtype=int32)